FROM ubuntu:jammy as spcharbuild
COPY external external
COPY common common
COPY character_recognition character_recognition
RUN apt update && apt install -y make g++ libboost-dev libpng-dev
RUN make -C character_recognition

FROM ubuntu:jammy as spchar
ENV SHOW_PRECENTAGE ""
COPY --from=spcharbuild build .
COPY docker/spchar.sh spchar.sh
RUN apt update && apt install -y libpng16-16
ENTRYPOINT ["./spchar.sh"]